workflows:
  build_app:
    name: Build FoudaMarket App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.2
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Force iOS Deployment Target to 12.0
        script: |
          cd ios
          if ! grep -q "platform :ios, '12.0'" Podfile; then
            sed -i.bak "1s/^/platform :ios, '12.0'\n/" Podfile
          fi
          cd ..

      - name: Debug CocoaPods sources
        script: |
          cd ios
          pod repo list
          pod search GoogleUtilities
          cd ..

      - name: Clean and update CocoaPods (iOS)
        script: |
          cd ios
          rm -rf ~/.cocoapods/repos
          rm -rf ~/Library/Caches/CocoaPods
          pod deintegrate
          pod cache clean --all
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..

      - name: Clean Flutter build
        script: |
          flutter clean

      - name: Print Flutter and Xcode versions
        script: |
          flutter --version
          xcodebuild -version

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

      - name: Build Android app
        script: |
          flutter build apk --release

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - build/app/outputs/flutter-apk/app-release.apk
