// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9pe0TzB8oJ__ldfjLJmwCm-2bWB4R9c',
    appId: '1:964251925023:web:4733815ca260ec1dd1332a',
    messagingSenderId: '964251925023',
    projectId: 'fouda-market',
    authDomain: 'fouda-market.firebaseapp.com',
    storageBucket: 'fouda-market.firebasestorage.app',
    measurementId: 'G-F14C25J8YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCKDgKuxibxkg3eyiZgUd3UgOzFwh99o',
    appId: '1:964251925023:android:d3844ee262f35a1ad1332a',
    messagingSenderId: '964251925023',
    projectId: 'fouda-market',
    storageBucket: 'fouda-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOPbNkB0cnYm5gXM7NfQrOj-Oux-Mo5s',
    appId: '1:964251925023:ios:8eb0d6319162e071d1332a',
    messagingSenderId: '964251925023',
    projectId: 'fouda-market',
    storageBucket: 'fouda-market.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

}
